### ISSUE TITLE
KolorScheme on Mac breaks tooltips

### ISSUE THREAD

**Issue by Moosems** [tukaan/tukaan#151]
### Describe the bug

Title is pretty self explanatory. Gives the error `tukaan.exceptions.TukaanTclError: Layout Tooltip not found`
```python
from tukaan import App, MainWindow, KolorScheme, Button
root = App()
window = MainWindow()


# Get clam theme
root.theme = KolorScheme # type: ignore


button = Button(window, text="", tooltip="Uh oh")
button.grid()


root.run()
```

Traceback:
```
Traceback (most recent call last):
  File "/Users/Moosems/Desktop/DIP-dev-Tukaan/test.py", line 10, in <module>
    button = Button(window, text="", tooltip="Uh oh")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/Moosems/Desktop/DIP-dev-Tukaan/venv/lib/python3.12/site-packages/tukaan/widgets/button.py", line 36, in __init__
    WidgetBase.__init__(
  File "/Users/Moosems/Desktop/DIP-dev-Tukaan/venv/lib/python3.12/site-packages/tukaan/_base.py", line 98, in __init__
    ToolTipProvider.add(self, tooltip)
  File "/Users/Moosems/Desktop/DIP-dev-Tukaan/venv/lib/python3.12/site-packages/tukaan/widgets/tooltip.py", line 40, in add
    cls.setup()
  File "/Users/Moosems/Desktop/DIP-dev-Tukaan/venv/lib/python3.12/site-packages/tukaan/widgets/tooltip.py", line 29, in setup
    Tcl.eval(None, "pack [ttk::label .tooltip.label -style Tooltip] -expand 1 -fill both")
  File "/Users/Moosems/Desktop/DIP-dev-Tukaan/venv/lib/python3.12/site-packages/tukaan/_tcl.py", line 226, in eval
    raise TukaanTclError(str(e)) from None
tukaan.exceptions.TukaanTclError: Layout Tooltip not found
```

### Expected behavior

Doesn't crash :D

### Operating system

macOS 13 (Ventura)

**Comment by rdbende** [comment]
## Expected behavior
KolorScheme cannot work on mac, and should not load.

**Comment by Moosems** [comment]
Interesting. It loads fine when I get rid of the tooltip. I'll make a note in the docs it isn't won't work on macs
