### ISSUE TITLE
AttributeError: partially initialized module 'tukaan' has no attribute 'App' (most likely due to a circular import)

### ISSUE THREAD

**Issue by lmjaedentai** [tukaan/tukaan#90]
I just follow the example given in [ReadMe ](https://github.com/tukaan/tukaan#get-started)to try this module at the first time.
```py
import tukaan

app = tukaan.App("My first Tukaan app")

app.run()
```
Then I get this error.
```py

(env) D:\Desktop\coding\sandbox>d:/Desktop/coding/discordpy/env/Scripts/python.exe d:/Desktop/coding/sandbox/tukaan.py
Traceback (most recent call last):
  File "d:\Desktop\coding\sandbox\tukaan.py", line 1, in <module>
    import tukaan
  File "d:\Desktop\coding\sandbox\tukaan.py", line 3, in <module>
    app = tukaan.App("My first Tukaan app")
AttributeError: partially initialized module 'tukaan' has no attribute 'App' (most likely due to a circular import)
```
I am new to this module and I have no idea about why would this happens.
Sorry for my incoveniences causes.

**Comment by lmjaedentai** [comment]
I accidentally named my file same as the module. Sorry
